#!/bin/bash
# Setup script to fetch API keys from GCP Secret Manager and create .env file

set -e  # Exit on error

echo "🔧 Kaimi Environment Setup"
echo "=========================="
echo ""

# Check if gcloud is installed
if ! command -v gcloud &> /dev/null; then
    echo "❌ Error: gcloud CLI is not installed"
    echo "   Install from: https://cloud.google.com/sdk/docs/install"
    exit 1
fi

# Check if authenticated
if ! gcloud auth list --filter=status:ACTIVE --format="value(account)" &> /dev/null; then
    echo "❌ Error: Not authenticated with gcloud"
    echo "   Run: gcloud auth login"
    exit 1
fi

# Check project is set to kaimi-seeker
CURRENT_PROJECT=$(gcloud config get-value project 2>/dev/null)
if [ "$CURRENT_PROJECT" != "kaimi-seeker" ]; then
    echo "⚠️  Current project: $CURRENT_PROJECT"
    echo "   Setting project to kaimi-seeker..."
    gcloud config set project kaimi-seeker
fi

echo "✅ Authenticated as: $(gcloud config get-value account)"
echo "✅ Project: kaimi-seeker"
echo ""

# Fetch secrets from Secret Manager
echo "📦 Fetching secrets from Secret Manager..."

SAM_API_KEY=$(gcloud secrets versions access latest --secret=samgov-api-key 2>/dev/null)
if [ -z "$SAM_API_KEY" ]; then
    echo "❌ Error: Could not fetch samgov-api-key"
    echo "   Make sure you have Secret Manager access"
    exit 1
fi
echo "✅ Retrieved SAM.gov API key"

GOOGLE_API_KEY=$(gcloud secrets versions access latest --secret=google-ai-studio-api-key 2>/dev/null)
if [ -z "$GOOGLE_API_KEY" ]; then
    echo "❌ Error: Could not fetch google-ai-studio-api-key"
    echo "   Make sure you have Secret Manager access"
    exit 1
fi
echo "✅ Retrieved Google AI Studio API key"

GOOGLE_DRIVE_CREDENTIALS_JSON=$(gcloud secrets versions access latest --secret=google-drive-service-account-key 2>/dev/null)
if [ -z "$GOOGLE_DRIVE_CREDENTIALS_JSON" ]; then
    echo "❌ Error: Could not fetch google-drive-service-account-key"
    echo "   Make sure you have Secret Manager access"
    exit 1
fi
echo "✅ Retrieved Google Drive service-account credentials"

GOOGLE_DRIVE_SHARED_DRIVE_ID=$(gcloud secrets versions access latest --secret=google-drive-shared-drive-id 2>/dev/null)
if [ -z "$GOOGLE_DRIVE_SHARED_DRIVE_ID" ]; then
    echo "❌ Error: Could not fetch google-drive-shared-drive-id"
    echo "   Make sure you have Secret Manager access"
    exit 1
fi
echo "✅ Retrieved Google Drive Shared Drive ID"

# Create .env file
echo ""
echo "📝 Creating .env file..."

cat > .env <<EOF
# Kaimi Environment Configuration
# Auto-generated by scripts/setup-env.sh
# DO NOT COMMIT THIS FILE

# SAM.gov API Key
SAM_API_KEY=$SAM_API_KEY

# Google AI Studio API Key (for Gemini agent platform - ADK Go)
GOOGLE_API_KEY=$GOOGLE_API_KEY

# Google Drive service-account credentials (for the Outline agent's Google Docs integration)
GOOGLE_DRIVE_CREDENTIALS_JSON=$GOOGLE_DRIVE_CREDENTIALS_JSON

# Shared Drive ID that the Outline agent creates Docs in
GOOGLE_DRIVE_SHARED_DRIVE_ID=$GOOGLE_DRIVE_SHARED_DRIVE_ID

# Hunter Configuration (optional - can also use command-line flags)
# MODE=cached
# NAICS_CODES=541512,541519
# STORE_PATH=./queue
EOF

echo "✅ Created .env file"
echo ""
echo "🎉 Setup complete!"
echo ""
echo "Your environment is ready. The .env file has been created with:"
echo "  - SAM_API_KEY"
echo "  - GOOGLE_API_KEY"
echo "  - GOOGLE_DRIVE_CREDENTIALS_JSON"
echo "  - GOOGLE_DRIVE_SHARED_DRIVE_ID"
echo ""
echo "To use these in your terminal session, run:"
echo "  source .env  (on Mac/Linux)"
echo "  or manually set the variables on Windows"
